apiVersion: v1
kind: Service
metadata:
  name: tacokumo-admin
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: tacokumo-admin
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.admin.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.admin.service.type }}
  ports:
    - port: {{ .Values.admin.service.port }}
      targetPort: {{ .Values.admin.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tacokumo-admin
    app.kubernetes.io/instance: {{ .Release.Name }}
