apiVersion: v1
kind: Service
metadata:
  name: tacokumo-admin-api
  labels:
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: tacokumo-admin-api
    app.kubernetes.io/instance: {{ .Release.Name }}