{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tacokumo-admin-ui
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: tacokumo-admin-ui
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.ui.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tacokumo-admin-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.ui.replicaCount }}
  template:
    metadata:
      annotations:
        {{- with .Values.ui.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: tacokumo-admin-ui
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- with .Values.ui.podLabels}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: tacokumo-admin-ui
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.ui.service.targetPort }}
            protocol: TCP
        {{- with .Values.ui.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.ui.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.ui.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.ui.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.ui.readinessProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.ui.resources | nindent 10 }}
        env:
          - name: NEXT_PUBLIC_API_BASE_URL
            value: {{ .Values.ui.config.apiBaseUrl }}
          - name: CORS_ORIGIN
            value: {{ .Values.ui.config.cors.origin | quote }}
          - name: CORS_METHODS
            value: {{ .Values.ui.config.cors.methods }}
          - name: CORS_ALLOW_HEADERS
            value: {{ .Values.ui.config.cors.allowHeaders }}
          - name: CORS_CREDENTIALS
            value: {{ .Values.ui.config.cors.credentials | quote }}
          - name: NODE_ENV
            value: "production"
          - name: NEXT_TELEMETRY_DISABLED
            value: "1"
          - name: PORT
            value: "3000"
          - name: HOSTNAME
            value: "0.0.0.0"
      serviceAccountName: {{ .Values.ui.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.ui.terminationGracePeriodSeconds }}
{{- end }}