apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-api
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: admin-api
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.api.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- with .Values.api.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  replicas: 1
  template:
    metadata:
      annotations:
        {{- with .Values.api.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: admin-api
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- with .Values.api.labels}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.api.podLabels}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        {{- if .Values.api.affinity }}
        {{- toYaml .Values.api.affinity | nindent 8 }}
        {{- else }}
        {}
        {{- end }}
      securityContext:
        {{- toYaml .Values.api.securityContext | nindent 8 }}
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - /manager
        args:
          {{- if .Values.api.serverContainer.extraArgs }}
          {{- range .Values.api.serverContainer.extraArgs }}
          - {{ . }}
          {{- end }}
          {{- end }}
        image: {{ .Values.api.serverContainer.image.repository }}:{{ .Values.api.serverContainer.image.tag }}
        name: manager
        ports: []
        securityContext:
          {{- toYaml .Values.api.serverContainer.securityContext | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.api.serverContainer.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.api.serverContainer.readinessProbe | nindent 10 }}
        resources: {{- toYaml .Values.api.serverContainer.resources | nindent 10 }}
        volumeMounts: []
      volumes: []
      serviceAccountName: {{ .Values.api.serviceAccount.name }}
      terminationGracePeriodSeconds: {{ .Values.api.terminationGracePeriodSeconds }}