{{- if .Values.api.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tacokumo-portal.fullname" . }}-api
  labels:
    {{- include "tacokumo-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type | default "ClusterIP" }}
  selector:
    {{- include "tacokumo-portal.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: 1323
      protocol: TCP
{{- end }}
