{{- if .Values.api.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tacokumo-portal.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tacokumo-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tacokumo-portal.fullname" . }}-api
subjects:
  - kind: ServiceAccount
    name: {{ include "tacokumo-portal.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
