apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.main.applicationName }}
  annotations:
    {{- with .Values.main.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      application: {{ .Values.main.applicationName }}
  template:
    metadata:
      labels:
        application: {{ .Values.main.applicationName }}
      annotations:
        {{- with .Values.main.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.main.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.main.applicationName }}
          image: "{{ .Values.main.image }}"
          imagePullPolicy: {{ .Values.main.imagePullPolicy }}
          {{- if .Values.main.service.enabled }}
          ports:
            {{- range .Values.main.service.ports }}
            - containerPort: {{ .targetPort | default .port }}
              protocol: {{ .protocol | default "TCP" }}
              {{- if .name }}
              name: {{ .name }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.main.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.main.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.main.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.main.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.main.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.main.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.main.startupProbe }}
          startupProbe:
            {{- toYaml .Values.main.startupProbe | nindent 12 }}
          {{- end }}