{{- if .Values.main.route.http.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.main.applicationName }}
  {{- with .Values.main.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.main.route.http.parentRefs }}
  parentRefs:
    {{- range .Values.main.route.http.parentRefs }}
    - name: {{ .name }}
      {{- if .namespace }}
      namespace: {{ .namespace }}
      {{- end }}
      {{- if .sectionName }}
      sectionName: {{ .sectionName }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- if .Values.main.route.http.hostnames }}
  hostnames:
    {{- range .Values.main.route.http.hostnames }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.main.route.http.rules }}
    - matches:
        {{- range .matches }}
        {{- if .path }}
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value | default "/" }}
        {{- end }}
        {{- if .headers }}
          headers:
            {{- range .headers }}
            - name: {{ .name }}
              type: {{ .type | default "Exact" }}
              value: {{ .value }}
            {{- end }}
        {{- end }}
        {{- end }}
      backendRefs:
        - name: {{ $.Values.main.applicationName }}
          port: {{ ($.Values.main.service.ports | first).port | default 80 }}
          weight: {{ .weight | default 100 }}
    {{- end }}
{{- end }}