api:
  serviceAccount:
    name: admin-api
  terminationGracePeriodSeconds: 10
  affinity: {}
  labels: {}
  annotations: 
    kubectl.kubernetes.io/default-container: server
  securityContext: {}
  podAnnotations: {}
  podLabels: 
    app.kubernetes.io/component: server
  imagePullSecrets: []
  serverContainer:
    image:
      repository: ghcr.io/tacokumo/admin-api
      tag: "latest"
    extraArgs: []
    livenessProbe: {}
    readinessProbe: {}
    securityContext: {}
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
