apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-controller-kubernetes-manager
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: portal-controller-kubernetes
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- with .Values.controller.labels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  replicas: 1
  template:
    metadata:
      annotations:
        {{- with .Values.controller.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.controller.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/name: portal-controller-kubernetes
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- with .Values.controller.labels}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.controller.podLabels}}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        {{- if .Values.controller.affinity }}
        {{- toYaml .Values.controller.affinity | nindent 8 }}
        {{- else }}
        {}
        {{- end }}
      securityContext:
        {{- toYaml .Values.controller.securityContext | nindent 8 }}
      {{- with .Values.controller.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
          {{- if .Values.controller.managerContainer.extraArgs }}
          {{- range .Values.controller.managerContainer.extraArgs }}
          - {{ . }}
          {{- end }}
          {{- end }}
        image: {{ .Values.controller.managerContainer.image.repository }}:{{ .Values.controller.managerContainer.image.tag }}
        name: manager
        ports: []
        securityContext:
          {{- toYaml .Values.controller.managerContainer.securityContext | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.controller.managerContainer.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controller.managerContainer.readinessProbe | nindent 10 }}
        resources: {{- toYaml .Values.controller.managerContainer.resources | nindent 10 }}
        volumeMounts: []
      volumes: []
      serviceAccountName: manager
      terminationGracePeriodSeconds: {{ .Values.controller.terminationGracePeriodSeconds }}
